name: veinmind-tools-scan
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'scan image'
        required: true
      imageId:
        description: 'scan image id'
      ep:
        description: 'oss entrypoint'
      ak:
        description: 'oss accessKey'
      sk:
        description: 'oss accessKeySecret'

jobs:
  scan:
    name: ${{ inputs.image }}
    runs-on: ubuntu-latest
    steps:
      - uses: chaitin/veinmind-action@main
        name: scan
        if: ${{ inputs.image != '' }}
        with:
          scan-action: scan-registry image
          image-ref: ${{ inputs.image }}
      - name: upload-result
        if: ${{ inputs.imageId != '' && inputs.ep != ''  && inputs.ak != '' && inputs.sk != ''  }}
        run: |
          wget http://gosspublic.alicdn.com/ossutil/1.7.14/ossutil64 && chmod 755 ossutil64
          ./ossutil64 config -e ${{inputs.ep}} -i ${{inputs.ak}} -k ${{inputs.sk}}
          ./ossutil64 cp report.json oss://veinmind-cache/${{inputs.imageId}}.json